/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan.transaksi;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import koneksi.Koneksi;
import tampilan.dashboard;



/**
 *
 * @author ACER
 */
public class pembelianStokObatForm extends javax.swing.JFrame {

    /**
     * Creates new form pembelianStokObatForm
     */
    public pembelianStokObatForm() {
        initComponents();
        loadSupplier ();
        loadPegawai ();
        initTabelObat ();
        loadObat ();
        cmbobat.setSelectedIndex(-1);  
        getTotalFromTable ();
        kosong ();
        dateTanggal.setMinSelectableDate(new java.util.Date());

    }
    
    protected void kosong(){ 
        cmbobat.setSelectedIndex(0);
        txtharga.setText("");
        txtjumlah.setText("");
        txtTotal.setText("");
    }
    private void initTabelObat() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Kode Obat");
    model.addColumn("Nama Obat");
    model.addColumn("Harga");
    model.addColumn("Jumlah");
    model.addColumn("Subtotal");

    tabelObat.setModel(model);
    }
    
private void loadObat() {
    try {
        Connection conn = koneksi.Koneksi.getConnection();
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT id_obat, nama_obat FROM obat");

        cmbobat.removeAllItems(); // kosongkan dulu
        while (rs.next()) {
            String kode = rs.getString("id_obat");
            String nama = rs.getString("nama_obat");
            cmbobat.addItem(kode + " - " + nama);
        }

        rs.close();
        stmt.close();
        // Jangan tutup koneksi di sini kalau mau dipakai lanjut!
        // conn.close(); ← HAPUS ini
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load obat: " + e.getMessage());
    }
}

     private void loadSupplier() {
    try {
        Connection conn = Koneksi.getConnection();
        java.sql.Statement stat = conn.createStatement(); 
        ResultSet rs = stat.executeQuery("SELECT id_supplier, nama_supplier FROM supplier");
        cmbSupplier.removeAllItems();
        while (rs.next()) {
            cmbSupplier.addItem(rs.getString("id_supplier") + " - " + rs.getString("nama_supplier"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load supplier: " + e.getMessage());
    }
    }
     
     private void loadPegawai() {
    try {
        Connection conn = Koneksi.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM pegawai");
        while (rs.next()) {
            cmbPegawai.addItem(rs.getInt("id_pegawai") + " - " + rs.getString("nama_pegawai"));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        cmbPegawai = new javax.swing.JComboBox<>();
        dateTanggal = new com.toedter.calendar.JDateChooser();
        btnsimpantransaksi = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btntambahobat = new javax.swing.JButton();
        cmbobat = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelObat = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnkembali = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 87, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 87, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pegawai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 87, -1));

        cmbSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbSupplierMouseClicked(evt);
            }
        });
        getContentPane().add(cmbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 162, 30));

        cmbPegawai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 162, 22));
        getContentPane().add(dateTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 192, 162, 30));

        btnsimpantransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsimpantransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-save-30.png"))); // NOI18N
        btnsimpantransaksi.setText("Simpan Transaksi");
        btnsimpantransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpantransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpantransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, -1, -1));

        btnhapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-30.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 740, -1, -1));

        btntambahobat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btntambahobat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-30.png"))); // NOI18N
        btntambahobat.setText("Tambah Obat");
        btntambahobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahobatActionPerformed(evt);
            }
        });
        getContentPane().add(btntambahobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 680, -1, -1));

        cmbobat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbobatActionPerformed(evt);
            }
        });
        getContentPane().add(cmbobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 162, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Obat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jumlah");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        txtharga.setEditable(false);
        txtharga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 162, -1));

        txtjumlah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjumlahKeyTyped(evt);
            }
        });
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 162, -1));

        tabelObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode ", "Nama Obat", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tabelObat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 162, -1));

        btnkembali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-30.png"))); // NOI18N
        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 740, -1, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 162, 38));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/8.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -150, 1950, 1380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahobatActionPerformed

    DefaultTableModel model = (DefaultTableModel) tabelObat.getModel();

    try {
        String kode = cmbobat.getSelectedItem().toString().split(" - ")[0]; // misal: "001 - Paracetamol"
        String nama = cmbobat.getSelectedItem().toString().split(" - ")[1];
        double harga = Double.parseDouble(txtharga.getText());
        int jumlah = Integer.parseInt(txtjumlah.getText());
        double subtotal = harga * jumlah;

        model.addRow(new Object[]{
            model.getRowCount() + 1,
            kode,
            nama,
            harga,
            jumlah,
            subtotal
        });

        hitungTotal(); // panggil fungsi hitung total
        kosong();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Isi semua data obat dengan benar!");
    }



 // TODO add your handling code here:
    }//GEN-LAST:event_btntambahobatActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnsimpantransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpantransaksiActionPerformed
    try {
        Connection conn = Koneksi.getConnection();
        DefaultTableModel model = (DefaultTableModel) tabelObat.getModel();

        // Ambil tanggal dari JDateChooser
        java.util.Date utilDate = dateTanggal.getDate();
        if (utilDate == null) {
            JOptionPane.showMessageDialog(this, "Tanggal belum diisi.");
            return;
        }
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        // Ambil ID dari ComboBox Supplier dan Pegawai
        String idSupplier = cmbSupplier.getSelectedItem().toString().split(" - ")[0];
        String idPegawai = cmbPegawai.getSelectedItem().toString().split(" - ")[0];

        // INSERT ke tabel pembelian (tanpa input id_pembelian, karena auto increment)
        String insertPembelian = "INSERT INTO pembelian (tanggal, id_supplier, id_pegawai, total) VALUES (?, ?, ?, ?)";
        PreparedStatement psPembelian = conn.prepareStatement(insertPembelian, Statement.RETURN_GENERATED_KEYS);
        psPembelian.setDate(1, sqlDate);
        psPembelian.setString(2, idSupplier);
        psPembelian.setString(3, idPegawai);
        psPembelian.setDouble(4, hitungTotal());
        if (tabelObat.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan! Harap isi tabel dengan data transaksi.");
        return;
        }
        
        psPembelian.executeUpdate();

        // Ambil id_pembelian terakhir yang barusan disimpan
        ResultSet generatedKeys = psPembelian.getGeneratedKeys();
        int idPembelian = -1;
        if (generatedKeys.next()) {
            idPembelian = generatedKeys.getInt(1);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mendapatkan ID pembelian.");
            return;
        }

        // Simpan data dari JTable ke tabel detail_pembelian
        for (int i = 0; i < model.getRowCount(); i++) {
            String idObat = model.getValueAt(i, 1).toString().trim();;  // kolom ke-1 = id_obat
            double harga = Double.parseDouble(model.getValueAt(i, 3).toString());
            int jumlah = Integer.parseInt(model.getValueAt(i, 4).toString());
            double subtotal = Double.parseDouble(model.getValueAt(i, 5).toString());

            String insertDetail = "INSERT INTO detail_pembelian (id_pembelian, id_obat, harga, jumlah, subtotal) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement psDetail = conn.prepareStatement(insertDetail);
            psDetail.setInt(1, idPembelian);
            psDetail.setString(2, idObat);
            psDetail.setDouble(3, harga);
            psDetail.setInt(4, jumlah);
                psDetail.setDouble(5, subtotal);
            psDetail.executeUpdate();
             String updateStok = "UPDATE obat SET stok = stok + ? WHERE id_obat = ?";
            PreparedStatement psUpdateStok = conn.prepareStatement(updateStok);
            psUpdateStok.setInt(1, jumlah);
            psUpdateStok.setString(2, idObat);
            psUpdateStok.executeUpdate();

        }
        

        JOptionPane.showMessageDialog(this, "Data pembelian berhasil disimpan!");
        

        // Kosongkan tabel dan form
        model.setRowCount(0);
        txtTotal.setText("");
        clearForm();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
        e.printStackTrace();
    }

    }//GEN-LAST:event_btnsimpantransaksiActionPerformed

    private void clearForm() {
    dateTanggal.setDate(null);
    cmbSupplier.setSelectedIndex(0);
    cmbPegawai.setSelectedIndex(0);
    txtTotal.setText("");
}

    private void cmbobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbobatActionPerformed
                                        
    try {
        Object selectedObj = cmbobat.getSelectedItem();
        if (selectedObj != null) {
            String selected = selectedObj.toString();
            int id_obat = Integer.parseInt(selected.split(" - ")[0]);
            
            Connection conn = Koneksi.getConnection();
            PreparedStatement ps = conn.prepareStatement("SELECT harga_beli FROM obat WHERE id_obat=?");
            ps.setInt(1, id_obat);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                txtharga.setText(String.valueOf(rs.getDouble("harga_beli")));
            }
        } else {
            // Optional: kosongkan harga kalau tidak ada yang dipilih
            txtharga.setText("");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }


    }//GEN-LAST:event_cmbobatActionPerformed

    private void cmbPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPegawaiActionPerformed
        
    }//GEN-LAST:event_cmbPegawaiActionPerformed

    private void cmbSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSupplierMouseClicked
        
    }//GEN-LAST:event_cmbSupplierMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
    int selectedRow = tabelObat.getSelectedRow();
    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) tabelObat.getModel();
        model.removeRow(selectedRow);
        hitungTotal();
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris obat yang ingin dihapus.");
    }


    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
    new dashboard().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyReleased
    try {
        int jumlah = Integer.parseInt(txtjumlah.getText());
        double harga = Double.parseDouble(txtharga.getText());
        double subtotal = jumlah * harga;
        txtTotal.setText(String.valueOf(subtotal));
    } catch (Exception e) {
        txtTotal.setText("0");
    }
    }//GEN-LAST:event_txtjumlahKeyReleased

    private void txtjumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyTyped
     char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume();
    }
    }//GEN-LAST:event_txtjumlahKeyTyped

    private void resetForm() {
    dateTanggal.setDate(null);
    cmbSupplier.setSelectedIndex(-1);
    cmbPegawai.setSelectedIndex(-1);
    cmbobat.setSelectedIndex(-1);
    txtharga.setText("");
    txtjumlah.setText("");
    txtTotal.setText("");

    DefaultTableModel model = (DefaultTableModel) tabelObat.getModel();
    model.setRowCount(0); // hapus semua baris
    }

private double hitungTotal() {
    double total = 0;
    for (int i = 0; i < tabelObat.getRowCount(); i++) {
        total += (double) tabelObat.getValueAt(i, 5); // Kolom Subtotal
    }
    lblTotal.setText("Total: Rp " + total);
    return total;
}

  private int getTotalFromTable() {
    int total = 0;
    DefaultTableModel model = (DefaultTableModel) tabelObat.getModel();
    int rowCount = model.getRowCount();
    
    for (int i = 0; i < rowCount; i++) {
        int subtotal = Integer.parseInt(model.getValueAt(i,3).toString().split("\\.")[0]);
        total += subtotal;
    }

    return total;
}

private void ambilHargaObat() {
    try {
        if (cmbobat.getSelectedItem() == null) return;

        String selected = cmbobat.getSelectedItem().toString();
        String kodeObat = selected.split(" - ")[0];

        Connection conn = koneksi.Koneksi.getConnection();
        PreparedStatement ps = conn.prepareStatement("SELECT harga_beli FROM obat WHERE id_obat = ?");
        ps.setString(1, kodeObat);

        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            double harga = rs.getDouble("harga_beli");
            txtharga.setText(String.valueOf(harga));
        }

        rs.close();
        ps.close();
        conn.close(); // Tutup koneksi DI SINI SAJA
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal ambil harga: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembelianStokObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembelianStokObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembelianStokObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembelianStokObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembelianStokObatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnsimpantransaksi;
    private javax.swing.JButton btntambahobat;
    private javax.swing.JComboBox<String> cmbPegawai;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JComboBox<String> cmbobat;
    private com.toedter.calendar.JDateChooser dateTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tabelObat;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    // End of variables declaration//GEN-END:variables
}
