/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan.transaksi;
import tampilan.dashboard;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
/**
 *
 * @author MyBook Hype AMD
 */
public class penjualanObatForm extends javax.swing.JFrame {
int selectedRow = -1;

    /**
     * Creates new form penjualanObatForm
     */
    public penjualanObatForm() {
        initComponents();
        loadPasien();
        loadObat();
        loadPegawai();
        setTableModel();
        hitungTotal();
        kosong();
    }
    protected void kosong(){ 
        cmbObat.setSelectedIndex(0);
        txtHarga.setText("");
        txtJumlah.setText("");
        txtSubtotal.setText("");
    }
    
private void setTableModel() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Obat");
    model.addColumn("Harga");
    model.addColumn("Jumlah");
    model.addColumn("Subtotal");
    tablePenjualan.setModel(model);
}

private void hitungTotal() {
    double total = 0;
    for (int i = 0; i < tablePenjualan.getRowCount(); i++) {
        total += (double) tablePenjualan.getValueAt(i, 3); // Kolom Subtotal
    }
    lblTotal.setText("Total: Rp " + total);
}

private int getTotalFromTable() {
    int total = 0;
    DefaultTableModel model = (DefaultTableModel) tablePenjualan.getModel();
    int rowCount = model.getRowCount();
    
    for (int i = 0; i < rowCount; i++) {
        int subtotal = Integer.parseInt(model.getValueAt(i,3).toString().split("\\.")[0]);
        total += subtotal;
    }

    return total;
}

 private void loadPasien() {
    try {
        Connection conn = Koneksi.getConnection();
        java.sql.Statement stat = conn.createStatement(); 
        
        // Mengambil ID Pasien dari tabel kunjungan dan mencocokkannya dengan nama di tabel pasien
        ResultSet rs = stat.executeQuery(
            "SELECT k.id_pasien, p.nama FROM kunjungan k JOIN pasien p ON k.id_pasien = p.id_pasien"
        );
        
        cmbPasien.removeAllItems();
        while (rs.next()) {
            cmbPasien.addItem(rs.getString("id_pasien") + " - " + rs.getString("nama"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load pasien: " + e.getMessage());
    }
}


private void loadObat() {
    try {
        Connection conn = Koneksi.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM obat");
        while (rs.next()) {
            cmbObat.addItem(rs.getInt("id_obat") + " - " + rs.getString("nama_obat"));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void loadPegawai() {
    try {
        Connection conn = Koneksi.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM pegawai");
        while (rs.next()) {
            cmbPegawai.addItem(rs.getInt("id_pegawai") + " - " + rs.getString("nama_pegawai"));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbPasien = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenjualan = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnSimpanTransaksi = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        cmbObat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbPegawai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Beli");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        txtJumlah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKeyTyped(evt);
            }
        });
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 225, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, -1, -1));

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 225, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        txtHarga.setEditable(false);
        txtHarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 225, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pasien");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        cmbPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cmbPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 225, -1));

        tablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePenjualan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, -1, -1));

        btnTambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-30.png"))); // NOI18N
        btnTambah.setText("Tambah Obat ");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, -1, -1));

        btnSimpanTransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSimpanTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-save-30.png"))); // NOI18N
        btnSimpanTransaksi.setText("Simpan Transaksi");
        btnSimpanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpanTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 640, -1, -1));

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-30.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 720, -1, -1));

        cmbObat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbObatActionPerformed(evt);
            }
        });
        getContentPane().add(cmbObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 225, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Obat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        lblTotal.setBackground(new java.awt.Color(204, 204, 255));
        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 284, 43));

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-30.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 720, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pegawai");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        cmbPegawai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 225, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2130, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanTransaksiActionPerformed

    try {
        Connection conn = Koneksi.getConnection();
        conn.setAutoCommit(false);

        // Simpan header
        String pasien = cmbPasien.getSelectedItem().toString();
        String id_pasien = pasien.split(" - ")[0];
        int id_pegawai = Integer.parseInt(cmbPegawai.getSelectedItem().toString().split(" - ")[0]); // Ganti sesuai sesi login
        // Date tanggal = new java.sql.Date(dateChooser == null ? null : dateChooser.getDate().getTime());
        
        PreparedStatement ps = conn.prepareStatement(
            "INSERT INTO penjualan (tanggal, id_pasien, id_pegawai, total) VALUES (?, ?, ?, ?)",
            Statement.RETURN_GENERATED_KEYS);
        ps.setDate(1, new java.sql.Date(System.currentTimeMillis()));
        ps.setString(2, id_pasien);
        ps.setInt(3, id_pegawai);
        ps.setDouble(4, getTotalFromTable());
        if (tablePenjualan.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan! Harap isi tabel dengan data transaksi.");
        return;
        }

        ps.executeUpdate();

        ResultSet rs = ps.getGeneratedKeys();
        int id_penjualan = 0;
        if (rs.next()) {
            id_penjualan = rs.getInt(1);
        }

        // Simpan detail
        for (int i = 0; i < tablePenjualan.getRowCount(); i++) {
            String obatStr = tablePenjualan.getValueAt(i, 0).toString();
            int id_obat = Integer.parseInt(obatStr.split(" - ")[0]);
            double harga = (double) tablePenjualan.getValueAt(i, 1);
            int jumlah = (int) tablePenjualan.getValueAt(i, 2);
            double subtotal = (double) tablePenjualan.getValueAt(i, 3);

            PreparedStatement psDetail = conn.prepareStatement(
            "INSERT INTO detail_penjualan (id_penjualan, id_obat, jumlah, harga, subtotal) VALUES (?, ?, ?, ?, ?)");
            psDetail.setInt(1, id_penjualan);
            psDetail.setInt(2, id_obat);
            psDetail.setInt(3, jumlah);
            psDetail.setDouble(4, harga);
            psDetail.setDouble(5, subtotal);
            psDetail.executeUpdate();

            // Kurangi stok obat
            PreparedStatement psUpdateStok = conn.prepareStatement(
                "UPDATE obat SET stok = stok - ? WHERE id_obat = ?");
            psUpdateStok.setInt(1, jumlah);
            psUpdateStok.setInt(2, id_obat);
            psUpdateStok.executeUpdate();
        }

        conn.commit();
        JOptionPane.showMessageDialog(null, "Transaksi berhasil disimpan");
        kosong();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal menyimpan transaksi" + e.getMessage());
    }


    }//GEN-LAST:event_btnSimpanTransaksiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
                                       
    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) tablePenjualan.getModel();
        model.removeRow(selectedRow); // Hapus baris
        selectedRow = -1; // Reset setelah dihapus
        hitungTotal(); // Panggil fungsi hitung ulang total jika ada
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!");
    }


    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyReleased

    try {
        int jumlah = Integer.parseInt(txtJumlah.getText());
        double harga = Double.parseDouble(txtHarga.getText());
        double subtotal = jumlah * harga;
        txtSubtotal.setText(String.valueOf(subtotal));
    } catch (Exception e) {
        txtSubtotal.setText("0");
    }


    }//GEN-LAST:event_txtJumlahKeyReleased

    private void cmbObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbObatActionPerformed

    try {
        String selected = cmbObat.getSelectedItem().toString();
        int id_obat = Integer.parseInt(selected.split(" - ")[0]);
        Connection conn = Koneksi.getConnection();
        PreparedStatement ps = conn.prepareStatement("SELECT harga_jual FROM obat WHERE id_obat=?");
        ps.setInt(1, id_obat);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            txtHarga.setText(String.valueOf(rs.getDouble("harga_jual")));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }


    }//GEN-LAST:event_cmbObatActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    DefaultTableModel model = (DefaultTableModel) tablePenjualan.getModel();
    String obat = cmbObat.getSelectedItem().toString();
    int jumlah = Integer.parseInt(txtJumlah.getText());
    double harga = Double.parseDouble(txtHarga.getText());
    double subtotal = harga * jumlah;

    model.addRow(new Object[]{obat, harga, jumlah, subtotal});
    hitungTotal();
    kosong();


    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed

        new dashboard().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cmbPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPegawaiActionPerformed

    private void tablePenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenjualanMouseClicked
    selectedRow = tablePenjualan.getSelectedRow();    
    }//GEN-LAST:event_tablePenjualanMouseClicked

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyTyped

    char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume();
    }

    }//GEN-LAST:event_txtJumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualanObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualanObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualanObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualanObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualanObatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpanTransaksi;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbObat;
    private javax.swing.JComboBox<String> cmbPasien;
    private javax.swing.JComboBox<String> cmbPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablePenjualan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
