/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import report.laporanPasien;
import report.laporanPembelianStokObat;
import report.laporanPenjualanObat;
import report.laporanStokObat;
import tampilan.transaksi.penjualanObatForm;
import tampilan.transaksi.pembelianStokObatForm;


/**
 *
 * @author MyBook Hype AMD
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPembelianStokObat = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelTransaksiPenjualanObat = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelLaporanPasien = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelLaporanPenjualan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panelLaporanPembelianStok = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panelLaporanStok = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelPasien = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelObat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelKunjungan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelPegawai = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelSupplier = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPembelianStokObat.setBackground(new java.awt.Color(255, 185, 113));
        panelPembelianStokObat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPembelianStokObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPembelianStokObatMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-transaction-50.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Transaksi Pembelian Stok Obat");

        javax.swing.GroupLayout panelPembelianStokObatLayout = new javax.swing.GroupLayout(panelPembelianStokObat);
        panelPembelianStokObat.setLayout(panelPembelianStokObatLayout);
        panelPembelianStokObatLayout.setHorizontalGroup(
            panelPembelianStokObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembelianStokObatLayout.createSequentialGroup()
                .addGroup(panelPembelianStokObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPembelianStokObatLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel10))
                    .addGroup(panelPembelianStokObatLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelPembelianStokObatLayout.setVerticalGroup(
            panelPembelianStokObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembelianStokObatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(panelPembelianStokObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 330, 120));

        panelTransaksiPenjualanObat.setBackground(new java.awt.Color(255, 185, 113));
        panelTransaksiPenjualanObat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTransaksiPenjualanObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTransaksiPenjualanObatMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-transaction-50.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Transaksi Penjualan Obat ");

        javax.swing.GroupLayout panelTransaksiPenjualanObatLayout = new javax.swing.GroupLayout(panelTransaksiPenjualanObat);
        panelTransaksiPenjualanObat.setLayout(panelTransaksiPenjualanObatLayout);
        panelTransaksiPenjualanObatLayout.setHorizontalGroup(
            panelTransaksiPenjualanObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiPenjualanObatLayout.createSequentialGroup()
                .addGroup(panelTransaksiPenjualanObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransaksiPenjualanObatLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel8))
                    .addGroup(panelTransaksiPenjualanObatLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel7)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelTransaksiPenjualanObatLayout.setVerticalGroup(
            panelTransaksiPenjualanObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiPenjualanObatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelTransaksiPenjualanObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 330, 120));

        panelLaporanPasien.setBackground(new java.awt.Color(61, 167, 123));
        panelLaporanPasien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLaporanPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLaporanPasienMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-report-50.png"))); // NOI18N
        jLabel11.setText("Laporan Pasien");

        javax.swing.GroupLayout panelLaporanPasienLayout = new javax.swing.GroupLayout(panelLaporanPasien);
        panelLaporanPasien.setLayout(panelLaporanPasienLayout);
        panelLaporanPasienLayout.setHorizontalGroup(
            panelLaporanPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanPasienLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 143, Short.MAX_VALUE))
        );
        panelLaporanPasienLayout.setVerticalGroup(
            panelLaporanPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLaporanPasienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        getContentPane().add(panelLaporanPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 290, 320, 80));

        panelLaporanPenjualan.setBackground(new java.awt.Color(61, 167, 123));
        panelLaporanPenjualan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLaporanPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLaporanPenjualanMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-report-50.png"))); // NOI18N
        jLabel12.setText("Laporan Penjualan Obat ");

        javax.swing.GroupLayout panelLaporanPenjualanLayout = new javax.swing.GroupLayout(panelLaporanPenjualan);
        panelLaporanPenjualan.setLayout(panelLaporanPenjualanLayout);
        panelLaporanPenjualanLayout.setHorizontalGroup(
            panelLaporanPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanPenjualanLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        panelLaporanPenjualanLayout.setVerticalGroup(
            panelLaporanPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        getContentPane().add(panelLaporanPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 390, 320, 80));

        panelLaporanPembelianStok.setBackground(new java.awt.Color(61, 167, 123));
        panelLaporanPembelianStok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLaporanPembelianStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLaporanPembelianStokMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-report-50.png"))); // NOI18N
        jLabel13.setText("Laporan Pembelian Stok Obat");

        javax.swing.GroupLayout panelLaporanPembelianStokLayout = new javax.swing.GroupLayout(panelLaporanPembelianStok);
        panelLaporanPembelianStok.setLayout(panelLaporanPembelianStokLayout);
        panelLaporanPembelianStokLayout.setHorizontalGroup(
            panelLaporanPembelianStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanPembelianStokLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        panelLaporanPembelianStokLayout.setVerticalGroup(
            panelLaporanPembelianStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        getContentPane().add(panelLaporanPembelianStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 490, 320, 80));

        panelLaporanStok.setBackground(new java.awt.Color(61, 167, 123));
        panelLaporanStok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLaporanStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLaporanStokMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-report-50.png"))); // NOI18N
        jLabel14.setText("Laporan Stok Obat ");

        javax.swing.GroupLayout panelLaporanStokLayout = new javax.swing.GroupLayout(panelLaporanStok);
        panelLaporanStok.setLayout(panelLaporanStokLayout);
        panelLaporanStokLayout.setHorizontalGroup(
            panelLaporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanStokLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 108, Short.MAX_VALUE))
        );
        panelLaporanStokLayout.setVerticalGroup(
            panelLaporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        getContentPane().add(panelLaporanStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 590, 320, 80));

        panelPasien.setBackground(new java.awt.Color(61, 167, 123));
        panelPasien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPasienMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-patient-50.png"))); // NOI18N
        jLabel2.setText("Pasien");

        javax.swing.GroupLayout panelPasienLayout = new javax.swing.GroupLayout(panelPasien);
        panelPasien.setLayout(panelPasienLayout);
        panelPasienLayout.setHorizontalGroup(
            panelPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelPasienLayout.setVerticalGroup(
            panelPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(panelPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 200, 80));

        panelObat.setBackground(new java.awt.Color(61, 167, 123));
        panelObat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelObatMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-medicine-50.png"))); // NOI18N
        jLabel3.setText("Obat");

        javax.swing.GroupLayout panelObatLayout = new javax.swing.GroupLayout(panelObat);
        panelObat.setLayout(panelObatLayout);
        panelObatLayout.setHorizontalGroup(
            panelObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        panelObatLayout.setVerticalGroup(
            panelObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelObatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        getContentPane().add(panelObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 200, 80));

        panelKunjungan.setBackground(new java.awt.Color(61, 167, 123));
        panelKunjungan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelKunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelKunjunganMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-people-50.png"))); // NOI18N
        jLabel6.setText("Kunjungan");

        javax.swing.GroupLayout panelKunjunganLayout = new javax.swing.GroupLayout(panelKunjungan);
        panelKunjungan.setLayout(panelKunjunganLayout);
        panelKunjunganLayout.setHorizontalGroup(
            panelKunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKunjunganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelKunjunganLayout.setVerticalGroup(
            panelKunjunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKunjunganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelKunjungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 200, 80));

        panelPegawai.setBackground(new java.awt.Color(61, 167, 123));
        panelPegawai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPegawaiMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-employee-50.png"))); // NOI18N
        jLabel5.setText("Pegawai");

        javax.swing.GroupLayout panelPegawaiLayout = new javax.swing.GroupLayout(panelPegawai);
        panelPegawai.setLayout(panelPegawaiLayout);
        panelPegawaiLayout.setHorizontalGroup(
            panelPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelPegawaiLayout.setVerticalGroup(
            panelPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 200, 80));

        panelSupplier.setBackground(new java.awt.Color(61, 167, 123));
        panelSupplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSupplierMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-supplier-50.png"))); // NOI18N
        jLabel4.setText("Supplier");

        javax.swing.GroupLayout panelSupplierLayout = new javax.swing.GroupLayout(panelSupplier);
        panelSupplier.setLayout(panelSupplierLayout);
        panelSupplierLayout.setHorizontalGroup(
            panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelSupplierLayout.setVerticalGroup(
            panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 200, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sejahtera I_dashboard.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(1280, 1080));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSupplierMouseClicked
        new supplierForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelSupplierMouseClicked

    private void panelPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPegawaiMouseClicked
        new pegawaiForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelPegawaiMouseClicked

    private void panelKunjunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKunjunganMouseClicked
        new kunjunganForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelKunjunganMouseClicked

    private void panelObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelObatMouseClicked
        new ObatForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelObatMouseClicked

    private void panelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPasienMouseClicked
        new pasienForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelPasienMouseClicked

    private void panelLaporanStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLaporanStokMouseClicked
        new laporanStokObat().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelLaporanStokMouseClicked

    private void panelLaporanPembelianStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLaporanPembelianStokMouseClicked
        new laporanPembelianStokObat().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelLaporanPembelianStokMouseClicked

    private void panelLaporanPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLaporanPenjualanMouseClicked
        new laporanPenjualanObat().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelLaporanPenjualanMouseClicked

    private void panelLaporanPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLaporanPasienMouseClicked
        new laporanPasien().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelLaporanPasienMouseClicked

    private void panelTransaksiPenjualanObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTransaksiPenjualanObatMouseClicked
        new penjualanObatForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelTransaksiPenjualanObatMouseClicked

    private void panelPembelianStokObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPembelianStokObatMouseClicked
        new pembelianStokObatForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelPembelianStokObatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelKunjungan;
    private javax.swing.JPanel panelLaporanPasien;
    private javax.swing.JPanel panelLaporanPembelianStok;
    private javax.swing.JPanel panelLaporanPenjualan;
    private javax.swing.JPanel panelLaporanStok;
    private javax.swing.JPanel panelObat;
    private javax.swing.JPanel panelPasien;
    private javax.swing.JPanel panelPegawai;
    private javax.swing.JPanel panelPembelianStokObat;
    private javax.swing.JPanel panelSupplier;
    private javax.swing.JPanel panelTransaksiPenjualanObat;
    // End of variables declaration//GEN-END:variables
}
