/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
/**
 *
 * @author MyBook Hype AMD
 */
public class kunjunganForm extends javax.swing.JFrame {

    /**
     * Creates new form kunjunganForm
     */
    public kunjunganForm() {
        initComponents();
        loadDataKunjungan();
        loadPasien();
        kosong();

    }
    
    private void loadPasien() {
    try {
        Connection conn = Koneksi.getConnection();
        java.sql.Statement stat = conn.createStatement(); 
        ResultSet rs = stat.executeQuery("SELECT id_pasien, nama FROM pasien");
        cmbPasien.removeAllItems();
        while (rs.next()) {
            cmbPasien.addItem(rs.getString("id_pasien") + " - " + rs.getString("nama"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load pasien: " + e.getMessage());
    }
}

private void kosong() {
    txtIdKunjungan.setText("");
    txtKeluhan.setText("");
    cmbPasien.setSelectedIndex(-1); 
    tanggalKunjungan.setDate(null); 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdKunjungan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKeluhan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbPasien = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tanggalKunjungan = new com.toedter.calendar.JDateChooser();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKunjungan = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Kunjungan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 140, -1));

        txtIdKunjungan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtIdKunjungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Keluhan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 120, -1));

        txtKeluhan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtKeluhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeluhanActionPerformed(evt);
            }
        });
        getContentPane().add(txtKeluhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pasien");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 130, -1));

        cmbPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPasienActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Kunjungan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 160, -1));

        tanggalKunjungan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tanggalKunjungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 180, -1));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-save-30.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 420, -1, -1));

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-edit-30.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 100, -1));

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-30.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 120, -1));

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-30.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 820, -1, -1));

        tabelKunjungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKunjungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKunjunganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKunjungan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 750, 236));

        txtCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 180, 40));

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-30.png"))); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sejahtera I (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKeluhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeluhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeluhanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    try {
        Connection conn = Koneksi.getConnection();
        String sql = "UPDATE kunjungan SET id_pasien=?, tanggal=?, keluhan=? WHERE id_kunjungan=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        String idPasien = cmbPasien.getSelectedItem().toString().split(" - ")[0];
        ps.setString(1, idPasien);
        Date selectedDate = tanggalKunjungan.getDate();
            if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Tanggal lahir belum dipilih!");
             return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            ps.setString(2, sdf.format(selectedDate));
            
        ps.setString(3, txtKeluhan.getText());
        ps.setString(4, txtIdKunjungan.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        loadDataKunjungan();
        kosong();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal edit: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void cmbPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPasienActionPerformed

    }//GEN-LAST:event_cmbPasienActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "INSERT INTO kunjungan (id_kunjungan, id_pasien, tanggal, keluhan) VALUES (?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, txtIdKunjungan.getText());
        String idPasien = cmbPasien.getSelectedItem().toString().split(" - ")[0];
        ps.setString(2, idPasien);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        ps.setString(3, sdf.format(tanggalKunjungan.getDate()));
        ps.setString(4, txtKeluhan.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data kunjungan disimpan");
        loadDataKunjungan();
        kosong();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
    }


    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "DELETE FROM kunjungan WHERE id_kunjungan=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, txtIdKunjungan.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        loadDataKunjungan();
        kosong();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
    }
    


    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelKunjunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKunjunganMouseClicked
   
    int row = tabelKunjungan.getSelectedRow();
    txtIdKunjungan.setText(tabelKunjungan.getValueAt(row, 0).toString());
    
    
    String namaPasienDariTabel = tabelKunjungan.getValueAt(row, 1).toString();


    for (int i = 0; i < cmbPasien.getItemCount(); i++) {
        String item = cmbPasien.getItemAt(i);
        if (item.contains(" - " + namaPasienDariTabel)) {
            cmbPasien.setSelectedIndex(i);
            break;
        }
    }

    String tglStr = tabelKunjungan.getValueAt(row, 2).toString();
    if (tglStr != null && !tglStr.isEmpty()) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(tglStr);
            tanggalKunjungan.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace(); 
            tanggalKunjungan.setDate(null);
        }
    } else {
        tanggalKunjungan.setDate(null);
    }
    txtKeluhan.setText(tabelKunjungan.getValueAt(row, 3).toString());


    }//GEN-LAST:event_tabelKunjunganMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
 
    new dashboard().setVisible(true);
    this.dispose();


    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String keyword = txtCari.getText().trim();
                if (!keyword.isEmpty()) {
                    cariDataKunjungan(keyword);
                } else {
                    loadDataKunjungan();
                }
            }
        });
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed

        String keyword = txtCari.getText().trim();
        if (!keyword.isEmpty()) {
            cariDataKunjungan(keyword);
        } else {
            loadDataKunjungan(); // method untuk reload semua data (kalau kamu punya)
        }

    }//GEN-LAST:event_btnCariActionPerformed

    private void loadDataKunjungan() {
    DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Pasien", "Tanggal", "Keluhan"}, 0);
    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT k.id_kunjungan, p.nama, k.tanggal, k.keluhan FROM kunjungan k JOIN pasien p ON k.id_pasien = p.id_pasien";
        java.sql.Statement stat = conn.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_kunjungan"),
                rs.getString("nama"),
                rs.getString("tanggal"),
                rs.getString("keluhan")
            });
        }
        tabelKunjungan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
}   

     private void cariDataKunjungan(String keyword) {
     Object[] Baris = {"ID", "Pasien", "Tanggal", "Keluhan"}; 
    DefaultTableModel model = new DefaultTableModel(null, Baris); 

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT k.id_kunjungan, p.nama, k.tanggal, k.keluhan " +
                     "FROM kunjungan k " +
                     "JOIN pasien p ON k.id_pasien = p.id_pasien " +
                     "WHERE k.id_kunjungan LIKE ? OR p.nama LIKE ? OR k.tanggal LIKE ? OR k.keluhan LIKE ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        String likeKeyword = "%" + keyword + "%";
        ps.setString(1, likeKeyword);
        ps.setString(2, likeKeyword);
        ps.setString(3, likeKeyword);
        ps.setString(4, likeKeyword);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_kunjungan"),
                rs.getString("nama"),
                rs.getString("tanggal"),
                rs.getString("keluhan")
            });
        }

        tabelKunjungan.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencari data: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kunjunganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kunjunganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kunjunganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kunjunganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kunjunganForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKunjungan;
    private com.toedter.calendar.JDateChooser tanggalKunjungan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdKunjungan;
    private javax.swing.JTextField txtKeluhan;
    // End of variables declaration//GEN-END:variables
}
