/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author MyBook Hype AMD
 */
public class ObatForm extends javax.swing.JFrame {

    /**
     * Creates new form ObatForm
     */
    public ObatForm() {
        initComponents();
        loadDataObat();
        kosong();
        cekObatAkanExpired();
        loadSupplier();
        
    }
 protected void kosong(){ 
        txtIdObat.setText("");
        txtNamaObat.setText("");
        txtStok.setText("");
        txtHargaJual.setText("");
        txtHargaBeli.setText("");
        tanggalExpired.setDate(null);
        cmbSupplier.setSelectedIndex(-1); 
    }
 
 private void loadSupplier() {
    try {
        Connection conn = Koneksi.getConnection();
        java.sql.Statement stat = conn.createStatement(); 
        ResultSet rs = stat.executeQuery("SELECT id_supplier, nama_supplier FROM supplier");
        cmbSupplier.removeAllItems();
        while (rs.next()) {
            cmbSupplier.addItem(rs.getString("id_supplier") + " - " + rs.getString("nama_supplier"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load supplier: " + e.getMessage());
    }
}
 
 private void cekObatAkanExpired() {
    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT nama_obat, tanggal_expired FROM obat WHERE tanggal_expired <= DATE_ADD(CURDATE(), INTERVAL 3 MONTH)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        StringBuilder pesan = new StringBuilder();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        while (rs.next()) {
            String namaObat = rs.getString("nama_obat");
            String tanggalExpired = rs.getString("tanggal_expired");
            pesan.append("Obat: ").append(namaObat)
                 .append(" akan expired pada: ").append(tanggalExpired).append("\n");
        }

        if (pesan.length() > 0) {
            JOptionPane.showMessageDialog(this,
                "Perhatian! Ada obat yang akan kedaluwarsa dalam 3 bulan:\n\n" + pesan.toString(),
                "Notifikasi Expired", JOptionPane.WARNING_MESSAGE);
        }

        rs.close();
        ps.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengecek obat yang akan expired: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNamaObat = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableObat = new javax.swing.JTable();
        txtStok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHargaJual = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdObat = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        tanggalExpired = new com.toedter.calendar.JDateChooser();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaObat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNamaObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaObatActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 206, -1));

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-30.png"))); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 570, 140, 43));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stok");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 64, 34));

        tableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Obat", "Nama Obat", "Stok", "Harga_Obat", "Harga_Jual", "Expired"
            }
        ));
        tableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableObatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableObat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 720, 941, 180));

        txtStok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStokKeyTyped(evt);
            }
        });
        getContentPane().add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 206, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Jual");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, -1, 34));

        txtHargaJual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaJualActionPerformed(evt);
            }
        });
        txtHargaJual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaJualKeyTyped(evt);
            }
        });
        getContentPane().add(txtHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 190, 206, -1));

        txtHargaBeli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHargaBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaBeliKeyTyped(evt);
            }
        });
        getContentPane().add(txtHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 300, 206, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga Beli");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 83, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Obat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 64, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Expired");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, 64, 34));

        txtIdObat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdObatActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 206, -1));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-save-30.png"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 140, 43));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Obat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 93, 34));

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-edit-30.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 120, 43));

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-30.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 930, -1, -1));

        tanggalExpired.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tanggalExpired, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 400, 206, 30));

        txtCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 162, 40));

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-30.png"))); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Supplier");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 64, 34));

        cmbSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cmbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 206, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sejahtera_obat.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaObatActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = Koneksi.getConnection();
                String sql = "DELETE FROM obat WHERE id_obat=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, txtIdObat.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                loadDataObat();
                kosong();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus data: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void tableObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableObatMouseClicked

        int row = tableObat.getSelectedRow();
        txtIdObat.setText(tableObat.getValueAt(row, 0).toString());
        txtNamaObat.setText(tableObat.getValueAt(row, 1).toString());
        txtStok.setText(tableObat.getValueAt(row, 2).toString());
        txtHargaJual.setText(tableObat.getValueAt(row, 3).toString());
        txtHargaBeli.setText(tableObat.getValueAt(row, 4).toString());
       String tglStr = tableObat.getValueAt(row, 5).toString();
if (tglStr != null && !tglStr.isEmpty()) {
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = sdf.parse(tglStr); 
        tanggalExpired.setDate(date);
    } catch (ParseException e) {
        e.printStackTrace(); // Boleh ditampilkan agar tahu jika format error
        tanggalExpired.setDate(null);
    }
} else {
    
    tanggalExpired.setDate(null); 
    
}
String supplierTabel = tableObat.getValueAt(row, 6).toString();

for (int i = 0; i < cmbSupplier.getItemCount(); i++) {
    String item = cmbSupplier.getItemAt(i);
    if (item.contains(supplierTabel)) {
        cmbSupplier.setSelectedIndex(i);
        break;
    }
}

    }//GEN-LAST:event_tableObatMouseClicked

    private void txtHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaJualActionPerformed

    private void txtIdObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdObatActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "INSERT INTO obat (id_obat, nama_obat, stok, harga_jual, harga_beli, tanggal_expired, id_supplier) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, txtIdObat.getText());
            ps.setString(2, txtNamaObat.getText());
            int stok = Integer.parseInt(txtStok.getText());
            ps.setInt(3, stok);
            ps.setDouble(4, Double.parseDouble(txtHargaJual.getText()));
            ps.setString(5, txtHargaBeli.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            ps.setString(6, sdf.format(tanggalExpired.getDate()));
            String idSupplier = cmbSupplier.getSelectedItem().toString().split(" - ")[0];
            ps.setString(7, idSupplier);
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Data obat berhasil disimpan!");
            loadDataObat();
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

    try {
        Connection conn = Koneksi.getConnection();
       String sql = "UPDATE obat SET nama_obat=?, stok=?, harga_jual=?, harga_beli=?, tanggal_expired=?, id_supplier=? WHERE id_obat=?";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, txtNamaObat.getText());
        int stok = Integer.parseInt(txtStok.getText());
        ps.setInt(2, stok);
        ps.setString(3, txtHargaJual.getText());
        ps.setString(4, txtHargaBeli.getText());

        Date selectedDate = (Date) tanggalExpired.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Tanggal expired belum dipilih!");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        ps.setString(5, sdf.format(selectedDate));

        // Ambil id_supplier dari combo box
        String selectedSupplier = (String) cmbSupplier.getSelectedItem();
        String idSupplier = selectedSupplier.split(" - ")[0]; // Ambil hanya ID-nya saja
        ps.setString(6, idSupplier);

        ps.setString(7, txtIdObat.getText());

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        loadDataObat();
        kosong();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal edit data: " + e.getMessage());
    }


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed

        new dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String keyword = txtCari.getText().trim();
                if (!keyword.isEmpty()) {
                    cariDataObat(keyword);
                } else {
                    loadDataObat();
                }
            }
        });
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed

        String keyword = txtCari.getText().trim();
        if (!keyword.isEmpty()) {
            cariDataObat(keyword);
        } else {
            loadDataObat();
        }

    }//GEN-LAST:event_btnCariActionPerformed

    private void txtStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStokKeyTyped

    char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume();
    }

    }//GEN-LAST:event_txtStokKeyTyped

    private void txtHargaJualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaJualKeyTyped

    char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume();
    }

    }//GEN-LAST:event_txtHargaJualKeyTyped

    private void txtHargaBeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaBeliKeyTyped

    char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume();
    }

    }//GEN-LAST:event_txtHargaBeliKeyTyped

      private void loadDataObat() {
     Object[] Baris ={"ID","Nama","Stok","Harga Jual","Harga Beli","Expired","Supplier"}; 
           DefaultTableModel model = new DefaultTableModel(null, Baris); 

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT o.id_obat, o.nama_obat, o.stok, o.harga_jual, o.harga_beli, o.tanggal_expired, s.nama_supplier " +
                     "FROM obat o JOIN supplier s ON o.id_supplier = s.id_supplier";
        java.sql.Statement stat = conn.createStatement(); 
        ResultSet rs = stat.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7)
            });
        }

        tableObat.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
      }
      
     private void cariDataObat(String keyword) {
    Object[] Baris = {"ID", "Nama Obat", "Stok", "Harga Jual", "Harga Beli", "Expired", "Supplier"}; 
    DefaultTableModel model = new DefaultTableModel(null, Baris);

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT o.id_obat, o.nama_obat, o.stok, o.harga_jual, o.harga_beli, "
                   + "o.tanggal_expired, s.nama_supplier "
                   + "FROM obat AS o JOIN supplier AS s ON o.id_supplier = s.id_supplier "
                   + "WHERE o.id_obat LIKE ? OR "
                   + "o.nama_obat LIKE ? OR "
                   + "o.stok LIKE ? OR "
                   + "o.harga_jual LIKE ? OR "
                   + "o.harga_beli LIKE ? OR "
                   + "o.tanggal_expired LIKE ? OR "
                   + "s.nama_supplier LIKE ?";

        PreparedStatement ps = conn.prepareStatement(sql);
        for (int i = 1; i <= 7; i++) {
            ps.setString(i, "%" + keyword + "%");
        }

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_obat"),
                rs.getString("nama_obat"),
                rs.getString("stok"),
                rs.getString("harga_jual"),
                rs.getString("harga_beli"),
                rs.getString("tanggal_expired"),
                rs.getString("nama_supplier")
            });
        }

        tableObat.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencari data: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableObat;
    private com.toedter.calendar.JDateChooser tanggalExpired;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtIdObat;
    private javax.swing.JTextField txtNamaObat;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
