/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import tampilan.dashboard;

/**
 *
 * @author ACER
 */
public class laporanPembelianStokObat extends javax.swing.JFrame {

    /**
     * Creates new form laporanPembelianStokObat
     */
    public laporanPembelianStokObat() {
        initComponents();
        loadDataPembelian ();
    }
    private void loadDataPembelian() {
    Object[] Baris = {"ID Pembelian", "Supplier", "Obat", "Jumlah", "Harga", "Subtotal"};
           DefaultTableModel model = new DefaultTableModel(null, Baris); 

    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT dp.id_pembelian, s.nama_supplier, CONCAT(o.id_obat, ' - ',  o.nama_obat) AS nama_obat, " +
                     "dp.jumlah, dp.harga, dp.subtotal " +
                     "FROM detail_pembelian dp " +
                     "JOIN pembelian p ON dp.id_pembelian = p.id_pembelian " +
                     "JOIN supplier s ON p.id_supplier = s.id_supplier " +
                     "JOIN obat o ON dp.id_obat = o.id_obat order by dp.id_pembelian asc";
        java.sql.Statement stat = conn.createStatement(); 
        ResultSet rs = stat.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6)
            });
        }

        tableLaporanPembelianStokObat.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLaporanPembelianStokObat = new javax.swing.JTable();
        btnkembali = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableLaporanPembelianStokObat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableLaporanPembelianStokObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tableLaporanPembelianStokObat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 1300, 390));

        btnkembali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-30.png"))); // NOI18N
        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 130, 60));

        btncetak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printing.png"))); // NOI18N
        btncetak.setText("Cetak");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        getContentPane().add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1481, 570, 120, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporanPembelianStokObat.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
       new dashboard().setVisible(true);
    this.dispose();            
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
      try(Connection conna = DriverManager.getConnection("jdbc:mysql://localhost:3306/apoteksejahtera", "root",""))
             {
                
                InputStream reportStream = getClass().getResourceAsStream("/report/laporanPembelianStokObat.jasper");

                
                HashMap<String, Object> parameters = new HashMap<>();
                parameters.put(JRParameter.REPORT_LOCALE, new Locale("id", "ID"));

                
                JasperPrint print = JasperFillManager.fillReport(reportStream, parameters, conna);

                JasperViewer viewer = new JasperViewer(print, false);
                viewer.setVisible(true);
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
    }//GEN-LAST:event_btncetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanPembelianStokObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanPembelianStokObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanPembelianStokObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanPembelianStokObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanPembelianStokObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnkembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLaporanPembelianStokObat;
    // End of variables declaration//GEN-END:variables
}
